In [33]:
import tensorflow as tf
import numpy as np
# import mlflow 

In [38]:
from sklearn.datasets import load_iris

'''
Class 0: Setosa
Class 1: Versicolor
Class 2: Virginica
'''

'\nClass 0: Setosa\nClass 1: Versicolor\nClass 2: Virginica\n'

In [35]:
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 


In [37]:
iris = load_iris()
X, y = iris.data, iris.target
print(X) 
print(y) 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42) 
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train) 
X_test = scaler.fit_transform(X_test) 


In [40]:
import joblib

# Save the scaler object to a file
joblib.dump(scaler, 'scaler.pkl')


['scaler.pkl']

In [6]:
# build the model 
model = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation='relu', input_shape=(4,)),
        tf.keras.layers.Dense(3, activation='softmax')
    ]
)


/Users/fourofour/Professional/Jio-2024/WarmHole/ops_env/lib/python3.11/site-packages/keras/src/layers/core/dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)


In [8]:
model.fit(
    X_train, y_train,
    epochs=10, 
    validation_data=(X_test, y_test)
)


Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.2429 - loss: 1.0782 - val_accuracy: 0.5667 - val_loss: 1.0280
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5627 - loss: 1.0168 - val_accuracy: 0.7667 - val_loss: 0.9706
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7329 - loss: 0.9621 - val_accuracy: 0.8333 - val_loss: 0.9169
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8125 - loss: 0.9150 - val_accuracy: 0.9333 - val_loss: 0.8665
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7565 - loss: 0.8726 - val_accuracy: 0.9333 - val_loss: 0.8202
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7488 - loss: 0.8455 - val_accuracy: 0.9333 - val_loss: 0.7766
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8106 - loss: 0.7752 - val_accuracy: 0.9000 - val_loss: 0.7350
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7921 - loss: 0.7534 - val_accuracy: 0.9000 - val_loss: 0.6970
Epoch 9

In [9]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9000 - loss: 0.6292


In [10]:
predictions = model.predict(X_test[:5])


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


In [11]:
predictions


array([[0.2347284 , 0.41803557, 0.3472361 ],
       [0.7152379 , 0.16166292, 0.12309914],
       [0.06846941, 0.33470222, 0.59682834],
       [0.22445552, 0.3933423 , 0.38220215],
       [0.19451861, 0.38820162, 0.41727975]], dtype=float32)

In [13]:
# Assume `new_sample` is the new input sample you want to predict
new_sample = [5.1, 3.5, 1.4, 0.2]


In [15]:
# Scale the new sample using the same scaler used for training
new_sample_scaled = scaler.transform([new_sample])
new_sample_scaled

array([[-1.05919085,  1.21615408, -1.37173756, -1.33370109]])

In [16]:
# Predict probabilities for each class
predictions = model.predict(new_sample_scaled)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


In [17]:
predictions 

array([[0.73066825, 0.16746283, 0.10186891]], dtype=float32)

In [20]:
# Get the predicted class (index of the class with highest probability)

predicted_class = np.argmax(predictions)

# Print the predicted class and corresponding probability
print("Predicted class:", predicted_class)
print("Probabilities:", predictions)


Predicted class: 0
Probabilities: [[0.73066825 0.16746283 0.10186891]]


In [26]:
# Serialize the model 

model.save("model.keras") 


# Load the Saved Model. 

In [29]:
# Load the model from the .keras file
loaded_model = tf.keras.models.load_model('model.keras')

# Assuming you have a new sample for prediction
new_sample = [5.1, 3.5, 1.4, 0.2] # Example new sample
new_sample_scaled = scaler.transform([new_sample])
new_sample_scaled

# Make predictions on the new sample
predictions = loaded_model.predict(new_sample_scaled)

# Get the predicted class (index of the class with highest probability)
predicted_class = tf.argmax(predictions, axis=-1).numpy()[0]

# Print the predicted class and corresponding probability
print("Predicted class:", predicted_class)
print("Probabilities:", predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
Predicted class: 0
Probabilities: [[0.73066825 0.16746283 0.10186891]]
